// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;

public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig apiKeyConfig;

    # Gets invoked to initialize the `connector`.
    #
    # + apiKeyConfig - API keys for authorization 
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ApiKeysConfig apiKeyConfig, ConnectionConfig config = {}, string serviceUrl = "https://generativelanguage.googleapis.com") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
        self.apiKeyConfig = apiKeyConfig.cloneReadOnly();
    }

    # Lists CachedContents.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function cacheServiceListCachedContents(map<string|string[]> headers = {}, *CacheServiceListCachedContentsQueries queries) returns ListCachedContentsResponse|error {
        string resourcePath = string `/v1beta/cachedContents`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates CachedContent resource.
    #
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function cacheServiceCreateCachedContent(CachedContent payload, map<string|string[]> headers = {}) returns CachedContent|error {
        string resourcePath = string `/v1beta/cachedContents`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Reads CachedContent resource.
    #
    # + cachedContent - The cachedContent id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function cacheServiceGetCachedContent(string cachedContent, map<string|string[]> headers = {}) returns CachedContent|error {
        string resourcePath = string `/v1beta/cachedContents/${getEncodedUri(cachedContent)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Deletes CachedContent resource.
    #
    # + cachedContent - The cachedContent id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function cacheServiceDeleteCachedContent(string cachedContent, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/v1beta/cachedContents/${getEncodedUri(cachedContent)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Updates CachedContent resource (only expiration is updatable).
    #
    # + cachedContent - The cachedContent id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function cacheServiceUpdateCachedContent(string cachedContent, CachedContent payload, map<string|string[]> headers = {}, *CacheServiceUpdateCachedContentQueries queries) returns CachedContent|error {
        string resourcePath = string `/v1beta/cachedContents/${getEncodedUri(cachedContent)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Lists all `Corpora` owned by the user.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceListCorpora(map<string|string[]> headers = {}, *RetrieverServiceListCorporaQueries queries) returns ListCorporaResponse|error {
        string resourcePath = string `/v1beta/corpora`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates an empty `Corpus`.
    #
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceCreateCorpus(Corpus payload, map<string|string[]> headers = {}) returns Corpus|error {
        string resourcePath = string `/v1beta/corpora`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Gets information about a specific `Corpus`.
    #
    # + corpora - The corpora id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceGetCorpus(string corpora, map<string|string[]> headers = {}) returns Corpus|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Deletes a `Corpus`.
    #
    # + corpora - The corpora id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceDeleteCorpus(string corpora, map<string|string[]> headers = {}, *RetrieverServiceDeleteCorpusQueries queries) returns error? {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Updates a `Corpus`.
    #
    # + corpora - The corpora id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceUpdateCorpus(string corpora, Corpus payload, map<string|string[]> headers = {}, *RetrieverServiceUpdateCorpusQueries queries) returns Corpus|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Lists all `Document`s in a `Corpus`.
    #
    # + corpora - The corpora id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceListDocuments(string corpora, map<string|string[]> headers = {}, *RetrieverServiceListDocumentsQueries queries) returns ListDocumentsResponse|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates an empty `Document`.
    #
    # + corpora - The corpora id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceCreateDocument(string corpora, Document payload, map<string|string[]> headers = {}) returns Document|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Gets information about a specific `Document`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceGetDocument(string corpora, string document, map<string|string[]> headers = {}) returns Document|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Deletes a `Document`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceDeleteDocument(string corpora, string document, map<string|string[]> headers = {}, *RetrieverServiceDeleteDocumentQueries queries) returns error? {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Updates a `Document`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceUpdateDocument(string corpora, string document, Document payload, map<string|string[]> headers = {}, *RetrieverServiceUpdateDocumentQueries queries) returns Document|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Lists all `Chunk`s in a `Document`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceListChunks(string corpora, string document, map<string|string[]> headers = {}, *RetrieverServiceListChunksQueries queries) returns ListChunksResponse|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}/chunks`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates a `Chunk`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceCreateChunk(string corpora, string document, Chunk payload, map<string|string[]> headers = {}) returns Chunk|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}/chunks`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Gets information about a specific `Chunk`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + chunk - The chunk id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceGetChunk(string corpora, string document, string chunk, map<string|string[]> headers = {}) returns Chunk|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}/chunks/${getEncodedUri(chunk)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Deletes a `Chunk`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + chunk - The chunk id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function retrieverServiceDeleteChunk(string corpora, string document, string chunk, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}/chunks/${getEncodedUri(chunk)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Updates a `Chunk`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + chunk - The chunk id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceUpdateChunk(string corpora, string document, string chunk, Chunk payload, map<string|string[]> headers = {}, *RetrieverServiceUpdateChunkQueries queries) returns Chunk|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}/chunks/${getEncodedUri(chunk)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Batch create `Chunk`s.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceBatchCreateChunks(string corpora, string document, BatchCreateChunksRequest payload, map<string|string[]> headers = {}) returns BatchCreateChunksResponse|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}/chunks:batchCreate`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Batch delete `Chunk`s.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceBatchDeleteChunks(string corpora, string document, BatchDeleteChunksRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}/chunks:batchDelete`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Batch update `Chunk`s.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceBatchUpdateChunks(string corpora, string document, BatchUpdateChunksRequest payload, map<string|string[]> headers = {}) returns BatchUpdateChunksResponse|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}/chunks:batchUpdate`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Performs semantic search over a `Document`.
    #
    # + corpora - The corpora id.
    # + document - The document id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceQueryDocument(string corpora, string document, QueryDocumentRequest payload, map<string|string[]> headers = {}) returns QueryDocumentResponse|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/documents/${getEncodedUri(document)}:query`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # + corpora - The corpora id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function permissionServiceListCorpusPermissions(string corpora, map<string|string[]> headers = {}, *PermissionServiceListCorpusPermissionsQueries queries) returns ListPermissionsResponse|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/permissions`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # + corpora - The corpora id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function permissionServiceCreateCorpusPermission(string corpora, Permission payload, map<string|string[]> headers = {}) returns Permission|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/permissions`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # + corpora - The corpora id.
    # + permission - The permission id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function permissionServiceGetCorpusPermission(string corpora, string permission, map<string|string[]> headers = {}) returns Permission|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/permissions/${getEncodedUri(permission)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # + corpora - The corpora id.
    # + permission - The permission id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function permissionServiceDeleteCorpusPermission(string corpora, string permission, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/permissions/${getEncodedUri(permission)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # + corpora - The corpora id.
    # + permission - The permission id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function permissionServiceUpdateCorpusPermission(string corpora, string permission, Permission payload, map<string|string[]> headers = {}, *PermissionServiceUpdateCorpusPermissionQueries queries) returns Permission|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}/permissions/${getEncodedUri(permission)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Performs semantic search over a `Corpus`.
    #
    # + corpora - The corpora id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function retrieverServiceQueryCorpus(string corpora, QueryCorpusRequest payload, map<string|string[]> headers = {}) returns QueryCorpusResponse|error {
        string resourcePath = string `/v1beta/corpora/${getEncodedUri(corpora)}:query`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # + dynamic - The dynamic id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceGenerateContentDynamic(string dynamic, GenerateContentRequest payload, map<string|string[]> headers = {}) returns GenerateContentResponse|error {
        string resourcePath = string `/v1beta/dynamic/${getEncodedUri(dynamic)}:generateContent`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # + dynamic - The dynamic id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceStreamGenerateContentDynamic(string dynamic, GenerateContentRequest payload, map<string|string[]> headers = {}) returns GenerateContentResponse|error {
        string resourcePath = string `/v1beta/dynamic/${getEncodedUri(dynamic)}:streamGenerateContent`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Lists the metadata for `File`s owned by the requesting project.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function fileServiceListFiles(map<string|string[]> headers = {}, *FileServiceListFilesQueries queries) returns ListFilesResponse|error {
        string resourcePath = string `/v1beta/files`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates a `File`.
    #
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function fileServiceCreateFile(CreateFileRequest payload, map<string|string[]> headers = {}) returns CreateFileResponse|error {
        string resourcePath = string `/v1beta/files`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Gets the metadata for the given `File`.
    #
    # + file - The file id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function fileServiceGetFile(string file, map<string|string[]> headers = {}) returns File|error {
        string resourcePath = string `/v1beta/files/${getEncodedUri(file)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Deletes the `File`.
    #
    # + file - The file id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function fileServiceDeleteFile(string file, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/v1beta/files/${getEncodedUri(file)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Download the `File`.
    #
    # + file - The file id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function fileServiceDownloadFile(string file, map<string|string[]> headers = {}) returns DownloadFileResponse|error {
        string resourcePath = string `/v1beta/files/${getEncodedUri(file)}:download`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Lists the [`Model`s](https://ai.google.dev/gemini-api/docs/models/gemini)
    # available through the Gemini API.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function modelServiceListModels(map<string|string[]> headers = {}, *ModelServiceListModelsQueries queries) returns ListModelsResponse|error {
        string resourcePath = string `/v1beta/models`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Gets information about a specific `Model` such as its version number, token
    # limits,
    # [parameters](https://ai.google.dev/gemini-api/docs/models/generative-models#model-parameters)
    # and other metadata. Refer to the [Gemini models
    # guide](https://ai.google.dev/gemini-api/docs/models/gemini) for detailed
    # model information.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function modelServiceGetModel(string model, map<string|string[]> headers = {}) returns Model|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Generates multiple embedding vectors from the input `Content` which
    # consists of a batch of strings represented as `EmbedContentRequest`
    # objects.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceBatchEmbedContents(string model, BatchEmbedContentsRequest payload, map<string|string[]> headers = {}) returns BatchEmbedContentsResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:batchEmbedContents`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generates multiple embeddings from the model given input text in a
    # synchronous call.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function textServiceBatchEmbedText(string model, BatchEmbedTextRequest payload, map<string|string[]> headers = {}) returns BatchEmbedTextResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:batchEmbedText`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Runs a model's tokenizer on a string and returns the token count.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function discussServiceCountMessageTokens(string model, CountMessageTokensRequest payload, map<string|string[]> headers = {}) returns CountMessageTokensResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:countMessageTokens`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Runs a model's tokenizer on a text and returns the token count.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function textServiceCountTextTokens(string model, CountTextTokensRequest payload, map<string|string[]> headers = {}) returns CountTextTokensResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:countTextTokens`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Runs a model's tokenizer on input `Content` and returns the token count.
    # Refer to the [tokens guide](https://ai.google.dev/gemini-api/docs/tokens)
    # to learn more about tokens.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceCountTokens(string model, CountTokensRequest payload, map<string|string[]> headers = {}) returns CountTokensResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:countTokens`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generates a text embedding vector from the input `Content` using the
    # specified [Gemini Embedding
    # model](https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding).
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceEmbedContent(string model, EmbedContentRequest payload, map<string|string[]> headers = {}) returns EmbedContentResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:embedContent`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generates an embedding from the model given an input message.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function textServiceEmbedText(string model, EmbedTextRequest payload, map<string|string[]> headers = {}) returns EmbedTextResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:embedText`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generates a grounded answer from the model given an input
    # `GenerateAnswerRequest`.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceGenerateAnswer(string model, GenerateAnswerRequest payload, map<string|string[]> headers = {}) returns GenerateAnswerResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:generateAnswer`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generates a model response given an input `GenerateContentRequest`.
    # Refer to the [text generation
    # guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed
    # usage information. Input capabilities differ between models, including
    # tuned models. Refer to the [model
    # guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning
    # guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceGenerateContent(string model, GenerateContentRequest payload, map<string|string[]> headers = {}) returns GenerateContentResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:generateContent`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generates a response from the model given an input `MessagePrompt`.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function discussServiceGenerateMessage(string model, GenerateMessageRequest payload, map<string|string[]> headers = {}) returns GenerateMessageResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:generateMessage`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generates a response from the model given an input message.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function textServiceGenerateText(string model, GenerateTextRequest payload, map<string|string[]> headers = {}) returns GenerateTextResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:generateText`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Performs a prediction request.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function predictionServicePredict(string model, PredictRequest payload, map<string|string[]> headers = {}) returns PredictResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:predict`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Same as Predict but returns an LRO.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function predictionServicePredictLongRunning(string model, PredictLongRunningRequest payload, map<string|string[]> headers = {}) returns Operation|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:predictLongRunning`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generates a [streamed
    # response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream)
    # from the model given an input `GenerateContentRequest`.
    #
    # + model - The model id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceStreamGenerateContent(string model, GenerateContentRequest payload, map<string|string[]> headers = {}) returns GenerateContentResponse|error {
        string resourcePath = string `/v1beta/models/${getEncodedUri(model)}:streamGenerateContent`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Lists created tuned models.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function modelServiceListTunedModels(map<string|string[]> headers = {}, *ModelServiceListTunedModelsQueries queries) returns ListTunedModelsResponse|error {
        string resourcePath = string `/v1beta/tunedModels`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates a tuned model.
    # Check intermediate tuning progress (if any) through the
    # [google.longrunning.Operations] service.
    #
    # Access status and results through the Operations service.
    # Example:
    # GET /v1/tunedModels/az2mb0bpw6i/operations/000-111-222
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function modelServiceCreateTunedModel(TunedModel payload, map<string|string[]> headers = {}, *ModelServiceCreateTunedModelQueries queries) returns Operation|error {
        string resourcePath = string `/v1beta/tunedModels`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Gets information about a specific TunedModel.
    #
    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function modelServiceGetTunedModel(string tunedModel, map<string|string[]> headers = {}) returns TunedModel|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Deletes a tuned model.
    #
    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function modelServiceDeleteTunedModel(string tunedModel, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Updates a tuned model.
    #
    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function modelServiceUpdateTunedModel(string tunedModel, TunedModel payload, map<string|string[]> headers = {}, *ModelServiceUpdateTunedModelQueries queries) returns TunedModel|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Lists permissions for the specific resource.
    #
    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function permissionServiceListPermissions(string tunedModel, map<string|string[]> headers = {}, *PermissionServiceListPermissionsQueries queries) returns ListPermissionsResponse|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}/permissions`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a permission to a specific resource.
    #
    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function permissionServiceCreatePermission(string tunedModel, Permission payload, map<string|string[]> headers = {}) returns Permission|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}/permissions`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Gets information about a specific Permission.
    #
    # + tunedModel - The tunedModel id.
    # + permission - The permission id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function permissionServiceGetPermission(string tunedModel, string permission, map<string|string[]> headers = {}) returns Permission|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}/permissions/${getEncodedUri(permission)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Deletes the permission.
    #
    # + tunedModel - The tunedModel id.
    # + permission - The permission id.
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function permissionServiceDeletePermission(string tunedModel, string permission, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}/permissions/${getEncodedUri(permission)}`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Updates the permission.
    #
    # + tunedModel - The tunedModel id.
    # + permission - The permission id.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function permissionServiceUpdatePermission(string tunedModel, string permission, Permission payload, map<string|string[]> headers = {}, *PermissionServiceUpdatePermissionQueries queries) returns Permission|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}/permissions/${getEncodedUri(permission)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceGenerateContentTunedModel(string tunedModel, GenerateContentRequest payload, map<string|string[]> headers = {}) returns GenerateContentResponse|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}:generateContent`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function textServiceGenerateTextTunedModel(string tunedModel, GenerateTextRequest payload, map<string|string[]> headers = {}) returns GenerateTextResponse|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}:generateText`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function generativeServiceStreamGenerateContentTunedModel(string tunedModel, GenerateContentRequest payload, map<string|string[]> headers = {}) returns GenerateContentResponse|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}:streamGenerateContent`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Transfers ownership of the tuned model.
    # This is the only way to change ownership of the tuned model.
    # The current owner will be downgraded to writer role.
    #
    # + tunedModel - The tunedModel id.
    # + headers - Headers to be sent with the request 
    # + payload - The request content.
    # + return - OK 
    remote isolated function permissionServiceTransferOwnership(string tunedModel, TransferOwnershipRequest payload, map<string|string[]> headers = {}) returns TransferOwnershipResponse|error {
        string resourcePath = string `/v1beta/tunedModels/${getEncodedUri(tunedModel)}:transferOwnership`;
        map<anydata> headerValues = {...headers};
        headerValues["x-goog-api-key"] = self.apiKeyConfig.xGoogAPIKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
